const body = document.body;
const card = document.createElement("div");
const cardImg = document.createElement("img");
const cardName = document.createElement("h1");
const cardCountry = document.createElement("h2");
const cardDesc = document.createElement("p");
const a1 = document.createElement("a");
const a2 = document.createElement("a");
const a3 = document.createElement("a");
const a4 = document.createElement("a");
const a5 = document.createElement("a");
card.classList.add("card");
cardImg.classList.add("card__img");
cardName.classList.add("card__name");
cardCountry.classList.add("card__country");
cardDesc.classList.add("card__desc");
a1.classList.add("card__link");
a2.classList.add("card__link");
a3.classList.add("card__link");
a4.classList.add("card__link");
a5.classList.add("card__link");
cardImg.setAttribute("src", "./img/profile-pic.png");
cardName.textContent = "Jessica Randall";
cardCountry.textContent = "London, United Kingdom";
cardDesc.textContent = `"Front-end developer and avid reader."`;
a1.textContent = "GitHub";
a2.textContent = "Frontend Mentor";
a3.textContent = "LinkedIn";
a4.textContent = "Instagram";
a5.textContent = "Twitter";
card.append(cardImg, cardName, cardCountry, cardDesc, a1, a2, a3, a4, a5);
body.appendChild(card);
